from typing import Union

import pytest
from hypothesis import settings

from .wrappers import libinfo_params

# TODO: apply deadline=None only to modin test cases
settings.register_profile("no_deadline", deadline=None)
settings.load_profile("no_deadline")


def pytest_generate_tests(metafunc):
    if "libinfo" in metafunc.fixturenames:
        metafunc.parametrize("libinfo", libinfo_params)


def pytest_addoption(parser):
    parser.addoption(
        "--ci",
        action="store_true",
        help="xfail and skip relevant tests for ../.github/workflows/test.yml",
    )
    # See https://github.com/HypothesisWorks/hypothesis/issues/2434
    parser.addoption(
        "--max-examples",
        action="store",
        default=None,
        help="set max examples generated by Hypothesis",
    )


def pytest_configure(config):
    max_examples: Union[None, str] = config.getoption("--max-examples")
    if max_examples is not None:
        settings.register_profile("max_examples", max_examples=int(max_examples))
        settings.load_profile("max_examples")


ci_failing_ids = [
    # dataframe objects return the interchange dataframe, not a dict, although
    # this is the behaviour that should be in the spec soon.
    # See https://github.com/data-apis/dataframe-api/pull/74
    "test_dataframe_object.py::test_toplevel_dunder_dataframe[pandas]",
    "test_dataframe_object.py::test_toplevel_dunder_dataframe[vaex]",
    "test_dataframe_object.py::test_toplevel_dunder_dataframe[modin]",
    "test_dataframe_object.py::test_dunder_dataframe[pandas]",
    "test_dataframe_object.py::test_dunder_dataframe[modin]",
    # vaex's interchange dataframe doesn't have __dataframe__()
    "test_dataframe_object.py::test_dunder_dataframe[vaex]",
    "test_signatures.py::test_dataframe_method[vaex-__dataframe__]",
    # https://github.com/vaexio/vaex/issues/2083
    # https://github.com/vaexio/vaex/issues/2093
    # https://github.com/vaexio/vaex/issues/2113
    "test_from_dataframe.py::test_from_dataframe_roundtrip[pandas-vaex]",
    "test_from_dataframe.py::test_from_dataframe_roundtrip[modin-vaex]",
    "test_from_dataframe.py::test_from_dataframe_roundtrip[vaex-pandas]",
    # https://github.com/vaexio/vaex/issues/2093
    "test_column_object.py::test_size[vaex]",
    # https://github.com/vaexio/vaex/issues/2118
    "test_column_object.py::test_dtype[vaex]",
    # Raises TypeError as opposed to RuntimeError, although this is the
    # behaviour that should be in the spec soon.
    # See https://github.com/data-apis/dataframe-api/pull/74
    "test_column_object.py::test_describe_categorical[pandas]",
    "test_column_object.py::test_describe_categorical[vaex]",
    "test_column_object.py::test_describe_categorical[cudf]",
    # https://github.com/pandas-dev/pandas/issues/47789
    "test_column_object.py::test_null_count[pandas]",
    # https://github.com/vaexio/vaex/issues/2120
    "test_column_object.py::test_null_count[vaex]",
    # https://github.com/modin-project/modin/issues/4687
    "test_column_object.py::test_null_count[modin]",
    # https://github.com/vaexio/vaex/issues/2121
    "test_column_object.py::test_get_chunks[vaex]",
    # https://github.com/vaexio/vaex/issues/2122
    "test_column_object.py::test_get_buffers[vaex]",
    # https://github.com/rapidsai/cudf/issues/11308
    "test_column_object.py::test_get_buffers[cudf]",
]


def pytest_collection_modifyitems(config, items):
    if config.getoption("--ci"):
        for item in items:
            if any(id_ in item.nodeid for id_ in ci_failing_ids):
                item.add_marker(pytest.mark.xfail())
